config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users

  resources :users
  resources :origins
  resources :tastings

  resources :batches do
    resources :tastings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batch.rb
class Batch < ActiveRecord::Base
  has_many :tastings
  belongs_to :origin
  attachment :artisan_image, type: :image
end

app/models/origin.rb
class Origin < ApplicationRecord
  has_many :tastings
  has_many :batches
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :tastings
  belongs_to :origin
end

app/models/tasting.rb
class Tasting < ApplicationRecord
  belongs_to :user
  belongs_to :batch, optional: true
  belongs_to :origin
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/batches_controller.rb
require 'json'

class BatchesController < ApplicationController
  before_action :authenticate_user!

  def index
    @batches = Batch.all
  end

  def show
    @batch = Batch.find(params[:id])
  end

  def new
    @batch = Batch.new
  end

  def create
    @batch = Batch.new(batch_params)
    json_object = JSON.parse(@batch.artisan_json)
    @batch["roast_length"] = json_object["computed"]["totaltime"]
    @batch["roast_length_pretty"] = seconds_to_time(@batch["roast_length"])
    @batch["dry_time"] = json_object["computed"]["DRY_time"]
    @batch["dry_time_percentage"] = percentage(@batch["dry_time"], @batch["roast_length"])

    @batch["malliard_time"] = json_object["computed"]["midphasetime"]
    @batch["malliard_time_percentage"] = percentage(@batch["malliard_time"], @batch["roast_length"])

    @batch["development_time"] = json_object["computed"]["finishphasetime"]
    @batch["development_time_percentage"] = percentage(@batch["development_time"], @batch["roast_length"])

    @batch["charge_temp"] = json_object["computed"]["CHARGE_BT"]
    @batch["drop_temp"] = json_object["computed"]["DROP_BT"]
    @batch["roast_date"] = DateTime.strptime(json_object["roastdate"],"%a %b %d %Y")

    @batch.save
    redirect_to @batch
  end

  private
    def batch_params
	    params.require(:batch).permit(:origin_id, :batch_number, :start_weight, :end_weight, :roast_date, :artisan_json, :artisan_image)
    end

    def seconds_to_time(seconds)
      [seconds / 60 % 60, seconds % 60].map { |t| t.to_s.rjust(2,'0') }.join(':')
    end

    def percentage(part, whole)
      part / whole
    end


end

app/controllers/origins_controller.rb
class OriginsController < ApplicationController
  before_action :authenticate_user!

  def index
    @origins = Origin.all
  end

  def show
    @origin = Origin.find(params[:id])
  end

  def new
  end

  def create
    @origin = Origin.new(origin_params)
    @origin.save
    redirect_to @origin
  end

  private
    def origin_params
      params.require(:origin).permit(:name, :region, :country, :processing_type, :elevation)
    end

end

app/controllers/tastings_controller.rb
class TastingsController < ApplicationController
  before_action :authenticate_user!

  SCAA_FIELDS = [:dry_fragrance,
		 :wet_aroma,
		 :flavor,
		 :aftertaste,
		 :acidity,
		 :body,
		 :balance,
		 :sweetness,
		 :uniformity,
                 :cleanliness ]

  def index
    @tastings = Tasting.all
  end

  def show
    @tasting = Tasting.find(params["id"])
  end

  def new
  end

  def create
    if params[:batch_id]
      @batch = Batch.find(params[:batch_id])
      @tasting = @batch.tastings.build(tasting_params)
      @tasting["user_id"] = current_user["id"]
      @tasting.save
      redirect_to batch_path(@batch)
    else
      puts tasting_params
      @tasting = Tasting.new(tasting_params)
      @tasting["total_score"] = calculate_total_score(@tasting)
      @tasting["user_id"] = current_user["id"]
      @tasting.save
      redirect_to tasting_path(@tasting)
    end
  end

  private
    def tasting_params
      params.require(:tasting).permit(:user_id,
				      :origin_id,
				      :batch_id,
				      :dry_fragrance,
				      :wet_aroma,
				      :flavor,
				      :aftertaste,
				      :acidity,
				      :body,
				      :balance,
				      :sweetness,
				      :uniformity,
				      :cleanliness,
				      :nose_notes,
				      :mouth_notes)
    end

    def calculate_total_score(tasting)
      total = 0
      SCAA_FIELDS.each do |field|
        total += tasting[field]
      end
      return total
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/origin_helper.rb
module OriginHelper
end

app/helpers/tastings_helper.rb
module TastingsHelper
end

app/views/batches/index.html.erb
<h1>Batches</h1>

<table class="table">
  <thead>
    <tr>
      <th>Coffee</th>
      <th>Origin</th>
      <th>Batch Number</th>
      <th>View Batch</th>
    </tr>
  </thead>

  <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= batch.origin.name %></td>
        <td><%= batch.origin.country %></td>
        <td><%= batch.batch_number %></td>
        <td><%= link_to 'View', batch_path(batch) %></td>
      </tr>
     <% end %>
  </tbody>
</table>

<p><%= link_to 'Import a batch', new_batch_path %></p>

app/views/batches/new.html.erb
<h1>Import a new Batch</h1>

<%= form_for @batch, :url => {:action => :create, :method => :post}, :html => {:multipart => true} do |form| %>
  <%= form.select :origin_id, options_from_collection_for_select(Origin.all, "id", "name") %>

  <p>
    <%= form.label :batch_number %><br>
    <%= form.text_field :batch_number %>
  </p>

  <p>
    <%= form.label :start_weight %><br>
    <%= form.text_field :start_weight %>
  </p>

  <p>
    <%= form.label :end_weight %><br>
    <%= form.text_field :end_weight %>
  </p>


  <p>
    <%= form.label :artisan_json %><br>
    <%= form.text_area :artisan_json %>
  </p>

  <p>
    <%= form.label :artisan_image%>
    <%= form.attachment_field :artisan_image %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/batches/show.html.erb
<h2> <%= @batch.origin.name %> </h2>
<p>
  Batch: <%= @batch.batch_number %>,  <%= localize(@batch.roast_date, :format => :concise) %>
  <% if @batch.artisan_image_id? %>
    <a href="<%=attachment_url(@batch, :artisan_image) %>">
      View artisan chart
    </a>
   <% end %>
</p>
<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: <%= number_to_percentage(@batch.dry_time_percentage * 100, precision: 0) %>" aria-valuemin="0" aria-valuemax="100"></div>
  <div class="progress-bar bg-success" role="progressbar" style="width: <%= number_to_percentage(@batch.malliard_time_percentage * 100, precision: 0) %>" aria-valuemin="0" aria-valuemax="100"></div>
  <div class="progress-bar bg-danger" role="progressbar" style="width: <%= number_to_percentage(@batch.development_time_percentage * 100, precision: 0) %>" aria-valuemin="0" aria-valuemax="100"></div>
</div>

<p>
  <strong>Origin Country:</strong>
    <%= @batch.origin.country %>
</p>

<p>
  <strong>Roast length:</strong>
    <%= @batch.roast_length_pretty %>
</p>

<p>
  <strong>Dry time:</strong>
    <%= number_to_percentage(@batch.dry_time_percentage * 100, precision: 1) %>
</p>

<p>
  <strong>Malliard time:</strong>
    <%= number_to_percentage(@batch.malliard_time_percentage * 100, precision: 1) %>
</p>

<p>
  <strong>Development time:</strong>
    <%= number_to_percentage(@batch.development_time_percentage * 100, precision: 1)%>
</p>

<p>
  <strong>Charge temp:</strong>
    <%= @batch.charge_temp %>
</p>

<p>
  <strong>Drop temp:</strong>
    <%= @batch.drop_temp %>
</p>

<p>
  <strong>Start weight:</strong>
    <%= @batch.start_weight %> grams
</p>

<p>
  <strong>End weight:</strong>
  <%= @batch.end_weight %> grams
</p>

<% if @batch.tastings.count > 0 %>
  <h2>Tastings</h2>

  <table class="table">
    <thead>
      <tr>
        <th>Total score</th>
        <th>User</th>
        <th>View tasting</th>
      </tr>
    </thead>

    <tbody>
      <% @batch.tastings.each do |tasting| %>
        <tr>
          <td><%= tasting.total_score %></td>
          <td><%= tasting.user.name %></td>
          <td><%= link_to 'View', tasting_path(tasting) %></td>
        </tr>
      <% end %>

    </tbody>
  </table>
<% end %>

<%= link_to 'See all batches', batches_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Coffees', origins_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Batches', batches_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Tastings', tastings_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>

<nav class="navbar navbar-expand-md navbar-light bg-light">
  <%= link_to "RoastingNotes™", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
       <%= render 'layouts/navigation_links' %>
       <%= render 'layouts/nav_links_for_auth' %>
    </ul>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Roaster Notes" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Roaster Notes" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/origins/index.html.erb
<h1>Coffees</h1>

<table class="table">
  <thead>
    <tr>
      <th>Coffee</th>
      <th>Region</th>
      <th>Country</th>
      <th>Processing Type</th>
      <th>View coffee</th>
    </tr>
  </thead>

  <tbody>

    <% @origins.each do |origin| %>
      <tr>
        <td><%= origin.name %></td>
        <td><%= origin.region %></td>
        <td><%= origin.country %></td>
        <td><%= origin.processing_type %></td>
        <td><%= link_to 'View', origin_path(origin) %></td>
      </tr>
    <% end %>

  </tbody>

</table>

<p><%= link_to 'Create a new coffee', new_origin_path %></p>

app/views/origins/new.html.erb
<h1>Create a new coffee</h1>

<%= form_with scope: :origin, url: origins_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :region %><br>
    <%= form.text_field :region %>
  </p>

  <p>
    <%= form.label :country %><br>
    <%= form.text_field :country %>
  </p>

  <p>
    <%= form.label :proecessing_type %><br>
    <%= form.text_field :processing_type %>
  </p>

  <p>
    <%= form.label :elevation %><br>
    <%= form.text_field :elevation %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/origins/show.html.erb
<h2> <%= @origin.name %> </h2>

<p>
  This will be the place where users will be able to view information related to a single coffee.
</p>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<em>RoastingNotes™ is created by coffee roasters, for coffee roasters.</em></br></br>

<h5>Why?</h5>
<p>
RoastingNotes™ was designed and created by a father and son coffee roasting team.
Coffee roasting was a hobby and they needed a place to store their roast data.
</p>

<h5>Credits</h5>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/profiles/new.html.erb
<h1>Import a new Roast Profile</h1>

<%= form_with scope: :profile, url: profiles_path, local: true do |form| %>
  <%= form.select :origin_id, options_from_collection_for_select(Origin.all, "id", "name") %>

  <p>
    <%= form.label :batch_number %><br>
    <%= form.text_field :batch_number %>
  </p>

  <p>
    <%= form.label :start_weight %><br>
    <%= form.text_field :start_weight %>
  </p>

  <p>
    <%= form.label :end_weight %><br>
    <%= form.text_field :end_weight %>
  </p>


  <p>
    <%= form.label :artisan_json %><br>
    <%= form.text_area :artisan_json %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tastings/index.html.erb
<h1>Tastings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Coffee</th>
      <th>Total score</th>
      <th>User</th>
      <th>View tasting</th>
    </tr>
  </thead>

  <tbody>
    <% @tastings.each do |tasting| %>
      <tr>
        <td><%= tasting.origin.name %></td>
        <td><%= tasting.total_score %></td>
        <td><%= tasting.user.name %></td>
        <td><%= link_to 'View', tasting_path(tasting) %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<p><%= link_to 'Record a new tasting', new_tasting_path %></p>

app/views/tastings/new.html.erb
<h1>Record a new tasting</h1>

<%= form_with scope: :tasting, url: tastings_path, local: true do |form| %>

  <div class="container">
    <div class="row">
      <div class="col-md">
        <div class="form-group">
          <%= form.select :origin_id, options_from_collection_for_select(Origin.all, "id", "name") %>
          <%= form.select :batch_id, options_from_collection_for_select(Batch.all, "id", "batch_number") %>
	</div>
        <div class="form-group">
          <%= form.label :dry_fragrance %>
          <%= number_field(:tasting, :dry_fragrance, in: 6.0..10.0, step: 0.25, class: "form-control") %>
        </div>

        <div class="form-group">
          <%= form.label :wet_aroma %>
          <%= number_field(:tasting, :wet_aroma, in: 6.0..10.0, step: 0.25, class: "form-control") %>
        </div>

        <div class="form-group">
          <%= form.label :flavor %>
          <%= number_field(:tasting, :flavor, in: 6.0..10.0, step: 0.25, class: "form-control") %>
        </div>

        <div class="form-group">
          <%= form.label :aftertaste %>
          <%= number_field(:tasting, :aftertaste, in: 6.0..10.0, step: 0.25, class: "form-control") %>
        </div>
        <div class="form-group">
          <%= form.label :acidity %>
          <%= number_field(:tasting, :acidity, in: 6.0..10.0, step: 0.25, class: "form-control") %>
        </div>
        <div class="form-group">
          <%= form.label :body %>
          <%= number_field(:tasting, :body, in: 6.0..10.0, step: 0.25, class: "form-control") %>
        </div>

        <div class="form-group">
          <%= form.label :balance %>
          <%= number_field(:tasting, :balance, in: 6.0..10.0, step: 0.25, class: "form-control") %>
        </div>

        <div class="form-group">
          <%= form.label :sweetness %>
          <%= number_field(:tasting, :sweetness, in: 6.0..10.0, step: 0.25, class: "form-control") %>
        </div>
        <div class="form-group">
          <%= form.label :uniformity %>
          <%= number_field(:tasting, :uniformity, in: 6.0..10.0, step: 0.25, class: "form-control") %>
        </div>

        <div class="form-group">
          <%= form.label :cleanliness %>
          <%= number_field(:tasting, :cleanliness, in: 6.0..10.0, step: 0.25, class: "form-control") %>
        </div>

        <div class="form-group">
          <%= form.label :nose_notes %><br>
          <%= form.text_area :nose_notes, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :mouth_notes %><br>
          <%= form.text_area :mouth_notes, class: "form-control" %>
      </div>

      <div class="form-group">
         <%= form.submit %>
      </div>

      <% end %>

      </div>
    </div>
  </div>

  </div>

app/views/tastings/show.html.erb
<h2> <%= @tasting.origin.name %> </h2>

<p>
  This is the place where users can view information about a specific cupping/tasting.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome to RoastingNotes™.</h3>

<p>RoastingNotes™ is a place for you to store, analyze, and evaluate coffee roasting data
from <a href="https://github.com/artisan-roaster-scope/artisan/blob/master/README.md" >Artisan</a> roasting software.</p>

<h4>Getting started is easy.</h4>
<ol>
  <li>First, <%= link_to 'add a new coffee', new_origin_path %>.</li>
  <li>Then <%= link_to 'upload a batch from artisan', new_batch_path %>.</li>
  <li>Finally, <%= link_to 'evaluate the batch', new_tasting_path %> by recording a tasting.</li>
</ol>

<h4>Some stats:</h4>
<ul>
  <li> <%= User.count %> user(s) registered. </li>
  <li> <%= Origin.count %> coffee(s). </li>
  <li> <%= Batch.count %> batch(es) imported. </li>
  <li> <%= Tasting.count %> tasting(s) recorded. </li>
</ul>